# Generated by Django 3.1.4 on 2021-03-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothName', models.CharField(max_length=100)),
                ('clothCover', models.CharField(max_length=1024)),
                ('clothPrice', models.FloatField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('userId', models.IntegerField()),
                ('matchStyle', models.CharField(max_length=520)),
            ],
        ),
    ]
