# Generated by Django 3.1.4 on 2021-03-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_addcloth_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcloth',
            name='category',
            field=models.CharField(default='全部', max_length=32),
        ),
    ]
