# Generated by Django 3.1.4 on 2021-03-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_addcloth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcloth',
            name='isAlreadyBought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addcloth',
            name='isCollect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addcloth',
            name='isPants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addcloth',
            name='isShoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addcloth',
            name='isUpperGarment',
            field=models.BooleanField(default=False),
        ),
    ]
