# Generated by Django 3.1.4 on 2021-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUnswer',
            fields=[
                ('unswerMessageId', models.IntegerField(primary_key=True, serialize=False)),
                ('masterName', models.CharField(max_length=1024)),
                ('masterIcon', models.CharField(max_length=1024)),
                ('masterDegree', models.CharField(max_length=64)),
                ('UnswerName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MatchProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userName', models.CharField(max_length=64)),
                ('userIcon', models.CharField(max_length=1024)),
                ('questionDetail', models.CharField(max_length=1024)),
                ('userShotId', models.IntegerField()),
                ('userOfferMoney', models.FloatField()),
                ('isUnswered', models.BooleanField(default=False)),
                ('unswerMessageId', models.IntegerField()),
                ('browseNum', models.IntegerField()),
                ('likeNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserShot',
            fields=[
                ('userShotId', models.IntegerField(primary_key=True, serialize=False)),
                ('shotUrl', models.CharField(max_length=1024)),
            ],
        ),
    ]
