# Generated by Django 3.1.4 on 2021-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchPro', '0002_auto_20210320_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterunswer',
            name='detailDescrip',
            field=models.TextField(default='详细搭配介绍', max_length=1024),
        ),
    ]
