# Generated by Django 3.1.4 on 2021-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchPro', '0003_masterunswer_detaildescrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerMessageId', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RenameField(
            model_name='masterunswer',
            old_name='unswerMessageId',
            new_name='answerMessageId',
        ),
    ]
