# Generated by Django 3.1.4 on 2021-03-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchPro', '0004_auto_20210320_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterUnswer',
            new_name='MasterAnswer',
        ),
        migrations.RenameField(
            model_name='masteranswer',
            old_name='UnswerName',
            new_name='AnswerName',
        ),
    ]
