# Generated by Django 3.1.4 on 2021-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchPro', '0006_auto_20210320_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchproblem',
            name='questionId',
            field=models.IntegerField(default=0),
        ),
    ]
