# Generated by Django 3.1.4 on 2021-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchPro', '0007_matchproblem_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchproblem',
            name='isUpload',
            field=models.BooleanField(default=False),
        ),
    ]
