# Generated by Django 3.1.4 on 2021-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothesHamper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('clothName', models.CharField(max_length=64)),
                ('clothurl', models.CharField(max_length=1024)),
                ('uploadTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
