# Generated by Django 3.1.4 on 2021-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBodyShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=64)),
                ('shot', models.CharField(max_length=1024)),
            ],
        ),
    ]
