# Generated by Django 3.1.4 on 2021-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isUse', models.BooleanField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('paixu', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('shopId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
