# Generated by Django 3.1.4 on 2021-03-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BluePrint',
            fields=[
                ('categoryId', models.IntegerField()),
                ('dataAdd', models.DateTimeField(auto_now_add=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
                ('fxType', models.IntegerField(default=0)),
                ('gotScore', models.IntegerField(default=5.0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1048)),
                ('minPrice', models.FloatField()),
                ('minScore', models.FloatField(default=1.0)),
                ('pic', models.CharField(max_length=1048)),
                ('recommendStatusStr', models.CharField(default='sale', max_length=128)),
                ('expertId', models.IntegerField(default=101)),
                ('statusStr', models.CharField(default='热卖中', max_length=64)),
                ('type', models.IntegerField(default=0)),
                ('userId', models.IntegerField(default=0)),
                ('authorName', models.CharField(default='tutu', max_length=64)),
                ('authorIcon', models.CharField(default='http://192.168.1.116:8087/static/authorIcons/icon1.png', max_length=1024)),
                ('likeNum', models.IntegerField(default=1.1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isUse', models.BooleanField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('paixu', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('shopId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.IntegerField(primary_key=True, serialize=False)),
                ('commentAuthorName', models.CharField(max_length=128)),
                ('AuthorIcon', models.CharField(max_length=1024)),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentLikeNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompriseImages',
            fields=[
                ('compriseImageId', models.IntegerField(primary_key=True, serialize=False)),
                ('imageName', models.CharField(max_length=128)),
                ('compriseImageUrl', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=1048)),
                ('detailDescrib', models.CharField(max_length=1048)),
                ('detailImages', models.IntegerField()),
                ('commentId', models.IntegerField()),
                ('commentNum', models.IntegerField()),
                ('compriseImageId', models.IntegerField()),
                ('tags', models.CharField(max_length=512)),
                ('likeNum', models.IntegerField()),
                ('collet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('businessId', models.IntegerField()),
                ('dataAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('linkUrl', models.CharField(max_length=1000)),
                ('paixu', models.IntegerField()),
                ('picUrl', models.CharField(max_length=1000)),
                ('remark', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=240)),
                ('type', models.CharField(max_length=200)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
