# Generated by Django 3.1.4 on 2021-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('businessId', models.IntegerField()),
                ('dataAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('linkUrl', models.CharField(max_length=1000)),
                ('paixu', models.IntegerField()),
                ('picUrl', models.CharField(max_length=1000)),
                ('remark', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=240)),
                ('type', models.CharField(max_length=200)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
