# Generated by Django 3.1.4 on 2021-02-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_swiper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
