# Generated by Django 3.1.4 on 2021-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluePrint',
            fields=[
                ('categoryId', models.IntegerField()),
                ('dataAdd', models.DateTimeField(auto_now_add=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
                ('fxType', models.IntegerField()),
                ('gotScore', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1048)),
                ('minPrice', models.FloatField()),
                ('minScore', models.FloatField()),
                ('pic', models.CharField(max_length=1048)),
                ('recommendStatusStr', models.CharField(max_length=128)),
                ('expertId', models.IntegerField()),
                ('statusStr', models.CharField(max_length=64)),
                ('type', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
