# Generated by Django 3.1.4 on 2021-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20210318_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterId', models.IntegerField()),
                ('masterName', models.CharField(max_length=64)),
                ('masterIcon', models.CharField(max_length=1024)),
                ('matchNum', models.IntegerField()),
                ('fans', models.FloatField()),
                ('followNum', models.FloatField()),
                ('collect', models.FloatField()),
                ('signature', models.TextField()),
            ],
        ),
    ]
