# Generated by Django 3.1.4 on 2021-03-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_masters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masters',
            old_name='masterIcon',
            new_name='masterCover',
        ),
    ]
