# Generated by Django 3.1.4 on 2021-02-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_blueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='expertId',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='fxType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='gotScore',
            field=models.IntegerField(default=5.0),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='minScore',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='recommendStatusStr',
            field=models.CharField(default='sale', max_length=128),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='statusStr',
            field=models.CharField(default='热卖中', max_length=64),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
