# Generated by Django 3.1.4 on 2021-03-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20210318_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='masterIcon',
            field=models.CharField(default='static/masterBluePrint/icons/icon1.png', max_length=1024),
        ),
    ]
