# Generated by Django 3.1.4 on 2021-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20210318_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='masterName',
            field=models.CharField(default='搭配师', max_length=64),
        ),
    ]
