# Generated by Django 3.1.4 on 2021-03-18 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_masters_mastername'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
