# Generated by Django 3.1.4 on 2021-03-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_matchdetail_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='masterDegree',
            field=models.CharField(default='大师', max_length=32),
        ),
    ]
