# Generated by Django 3.1.4 on 2021-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_masterprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterDetailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterId', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=1024)),
            ],
        ),
    ]
