# Generated by Django 3.1.4 on 2021-03-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_masterprintdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterprintdetail',
            old_name='printName',
            new_name='name',
        ),
    ]
