# Generated by Django 3.1.4 on 2021-03-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20210320_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompriseImages',
        ),
    ]
