# Generated by Django 3.1.4 on 2021-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_delete_compriseimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompriseImages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('compriseImageId', models.IntegerField()),
                ('imageName', models.CharField(max_length=128)),
                ('compriseImageUrl', models.CharField(max_length=1024)),
            ],
        ),
    ]
