# Generated by Django 3.1.4 on 2021-03-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_compriseimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueprint',
            old_name='id',
            new_name='printId',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='fxType',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='minScore',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='recommendStatusStr',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='statusStr',
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='type',
            field=models.CharField(default='0', max_length=1024),
        ),
    ]
