# Generated by Django 3.1.4 on 2021-03-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0020_remove_blueprint_gotscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailimages',
            old_name='userId',
            new_name='printId',
        ),
    ]
