# Generated by Django 3.1.4 on 2021-03-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_auto_20210322_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compriseimages',
            old_name='id',
            new_name='printId',
        ),
    ]
