# Generated by Django 3.1.4 on 2021-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0022_auto_20210322_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='isUpload',
            field=models.BooleanField(default=False),
        ),
    ]
